CREATE TABLE dept
( deptNo NUMERIC(2) PRIMARY KEY,
  dName VARCHAR(14) NOT NULL,
  location VARCHAR(13))
/
CREATE TABLE emp
( EMPNO NUMERIC(4) PRIMARY KEY,
  ENAME VARCHAR(10) NOT NULL,
  JOB VARCHAR(9),
  MGR NUMERIC(4),
  HIREDATE DATETIME,
  SALARY NUMERIC(7, 2),
  DEPTNO NUMERIC(2) REFERENCES dept(deptNo) ON DELETE CASCADE)
/
